### PR TITLE
v3 - Would love input on new changes

### PR DESCRIPTION
**Pull request by josmithua**
- Add `getAccount(accountIdentifier)` method
- Add `getAccounts()` method
- Add `signoutFromBrowser: boolean` option to `signOut` method params
- `authority` is optional for `acquireToken` and `acquireTokenSilent` method params

BREAKING CHANGE:
- Change `MSALCLient` class name to `PublicClientApplication`
- `PublicClientApplication` constructor takes config object
- webview parameters for `acquireToken` and `signOut` methods are now
passed in via an optional nested `webviewParameters` object
- `acquireTokenSilent` and `signOut` methods require an `MSALAccount` object
instead of `accountIdentifier` string
- `removeAccount` method takes a single `MSALAccount` object

### CODE REVIEW

**Comment by josmithua** [comment]
@jasonnutter @WolfyUK @torekymilan @seanfriedman1994 If any of you are using this library, do you think you could install the beta and provide some feedback? I would really appreciate it!

`yarn add react-native-msal@beta`

**Comment by WolfyUK** [comment]
Sounds great. I'm away at the moment but happy to review in September.

**Comment by WolfyUK** [comment]
@josmithua Today I managed to upgrade one of our playgrounds to use the latest beta version and all seems to work well. I didn't go to the extent of implementing the full B2C version with password reset etc., as per the supplied example, but the production app already covers most of what the example contains (albeit without the new `knownAuthorities` property). I really like the 'default' authority so you don't have to manage this in multiple places, and refactoring to create `MSALWebviewParams` helps with the UX extensibility.

As I was going through the upgrade I made some notes that you can see in [this commit](https://github.com/TheDataShed/react-native-msal/commit/9aceaea34c3e8b3a78f4d845f61d8d7a8b623bfa). Is it worth pulling something like this through once v3 is out of beta?

**Comment by josmithua** [comment]
@WolfyUK Thanks a lot for your feedback! Yes, I definitely think the CHANGELOG is worth pulling in, and we should add a link to it from the README: "Migrating from v2 to v3"

**Comment by WolfyUK** [comment]
If you like I can add that link in and submit a PR to the `beta` branch.

**Pull request merged**
