### PR TITLE
Convert Android sources to plain Java

### PR DESCRIPTION
**Pull request by friederbluemle**
## Summary

There are no functional changes in this PR. Instead, it's a conversion of the Android native module source code into **plain Java**, _removing_ the dependency on `kotlin-stdlib`.

## Details

React Native is somewhat unique in the way it handles distribution and usage of Android library projects (i.e. React Native native modules): They are downloaded (and extracted) **as source code**, and compiled whenever a React Native app is built. That's different from the "usual" way of distributing Android libraries **in precompiled binary form**.

Every library (with all its dependencies) has to play nicely with every other library that is part of the overall build. Most of the time this works out just fine, however problems can occur especially when projects become outdated, or there are dependency and/or build tool conflicts.

A standalone library project can't possibly know all possible contexts it is being used in, and it is important to keep the code, build, and dependency structure as plain and simple as possible.

## Impact

In terms of raw number of lines of code, we're looking at a slight increase (no surprise, as Java in general is a bit more verbose than Kotlin). However, navigating through the sources in the context of the Android framework, the React Native Android sources, as well as the Microsoft Authentication Library (msal) feels more aligned and homogenous. All three are entirely written in plain Java as well.

There is no impact and no changes are required on the consumer side. Applications based on the default React Native template (which does _not_ include kotlin-stdlib) may notice a slight **decrease** in binary app size, as well as a **lowered** method count (unless it's transitively pulled in). Clean build time might be minimally faster. Perhaps most importantly, the removal of this dependency will increase compatibility with other libraries and reduce the risk of dependency conflicts.

### CODE REVIEW

**Comment by josmithua** [comment]
Hey Frieder, thanks for your pull request! I'm fine with this.

Have you tested your changes in the example app or another app?

**Comment by friederbluemle** [comment]
Hey Joshua, thanks for taking a look and the fast reply!

Yes, I've tested it using the `example` app included in the repo. I clicked "Sign In", got the response with the access token etc, clicked "Acquire Token", and finally "Sign Out". Everything appears to work correctly (no difference in behavior, as expected). That said, I am not deeply familiar with how msal works - do you have any suggestion for additional testing?

**Comment by josmithua** [comment]
I think that’s fine. Just want to make sure nothing unexpected happened when you converted the source. I’m guessing you used Android Studio’s converter?

**Comment by friederbluemle** [comment]
The code (module and package) was converted in Android Studio, but mostly manually. It wasn't that much code, so it took less than an hour. Plus, I don't think it's possible to convert Java<->Kotlin in an automated way that results in clean and idiomatic code.
The methods in `FileUtils` on the other hand were directly copied from `org.apache.commons.io` (_without_ converting them in Android Studio). Thanks for leaving a comment in that file which made it much easier for me to find the original source :+1: I updated the [existing comment](https://github.com/stashenergy/react-native-msal/blob/47654e3935a9be614bb19a59a37514ce770db6a0/android/src/main/java/com/reactnativemsal/FileUtils.kt#L7) "`[...] and converted to Kotlin via Android Studio tools.`" as that's no longer the case. :)

**Comment by josmithua** [comment]
Yeah the converter doesn't produce the nicest code sometimes. I appreciate the manual labor :).

I'll try and get this merged on the weekend.

**Comment by friederbluemle** [comment]
Great thanks!

I'll also work on a few small updates to the example and possibly some unit tests for native code in parallel.

**Pull request merged**
